language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ln' ]; then cd .. && eval "mv $currentfolder generator-ln" && cd generator-ln; fi
